 ---------------------------------------------TẠO DATABASE------------------------------------
create database QL_CUAHANGTIENLOI
use QL_CUAHANGTIENLOI
go
SET DATEFORMAT dmy; 
-----------------------------TẠO BẢNG VÀ CÁC TRIGGER RÀNG BUỘC------------------------------
CREATE TABLE NGUOIDUNG
(
			ID_DN			VARCHAR(10) NOT NULL,
			MATKHAU			VARCHAR(50),
			TEN  			NVARCHAR(50),
			SDT				VARCHAR(10),
			DIACHI			NVARCHAR(100),
			GIOITINH		NVARCHAR(10),
			NGAYSINH		DATE,
			TINHTRANG		BIT,
			HINH			NVARCHAR(50),
			CONSTRAINT PK_NGUOIDUNG PRIMARY KEY(ID_DN)				
);

CREATE TABLE MANHINH
(
			ID_MANHINH		INT IDENTITY NOT NULL,
			TENMANHINH		VARCHAR(50),
			CONSTRAINT PK_MANHINH PRIMARY KEY(ID_MANHINH)				
);

CREATE TABLE NHOMNGUOIDUNG
(
			ID_NHOM			VARCHAR(10) NOT NULL,
			TENNHOM			NVARCHAR(50),
			CONSTRAINT PK_NND PRIMARY KEY(ID_NHOM),
);

CREATE TABLE NGUOIDUNGNHOMNGUOIDUNG
(
			ID_NHOM			VARCHAR(10) NOT NULL,
			ID_DN			VARCHAR(10) NOT NULL,
			GHICHU			NVARCHAR(50),
			CONSTRAINT PK_NNND PRIMARY KEY(ID_NHOM, ID_DN),
			CONSTRAINT FK_NNND_ND FOREIGN KEY (ID_DN) REFERENCES NGUOIDUNG(ID_DN),
			CONSTRAINT FK_NNND_NND FOREIGN KEY (ID_NHOM) REFERENCES NHOMNGUOIDUNG(ID_NHOM)
);

CREATE TABLE PHANQUYEN
(
			ID_NHOM			VARCHAR(10) NOT NULL,
			ID_MANHINH		INT NOT NULL,
			GHICHU			VARCHAR(20),
			COQUYEN			BIT,
			CONSTRAINT PK_PHANQUYEN PRIMARY KEY(ID_NHOM, ID_MANHINH),
			CONSTRAINT FK_PQ_MH FOREIGN KEY (ID_MANHINH) REFERENCES MANHINH(ID_MANHINH),
			CONSTRAINT FK_PQ_NNDA FOREIGN KEY (ID_NHOM) REFERENCES NHOMNGUOIDUNG(ID_NHOM)
);


CREATE TABLE NHACUNGCAP
(
			ID_NCC			INT IDENTITY NOT NULL,
			TENNCC			NVARCHAR(50),
			DIACHI  		NVARCHAR(100),
			SDT				VARCHAR(10),
			CONSTRAINT PK_NCC PRIMARY KEY(ID_NCC)
				
);



CREATE TABLE KHACHHANG
( 
            ID_KH             INT IDENTITY NOT NULL,
            TENKH             NVARCHAR(100),
            GIOITINH          NVARCHAR(5),
            DIACHI            NVARCHAR(100),
            SDT		          VARCHAR(10),
			DIEM			  INT,
			CONSTRAINT PK_MaKH PRIMARY KEY(ID_KH)
 );

 CREATE TABLE LOAISANPHAM
 (
			ID_LSP				INT IDENTITY NOT NULL,
			TENLOAISANPHAM		NVARCHAR(100),
			CONSTRAINT PK_LOAISP PRIMARY KEY(ID_LSP)
 );


 CREATE TABLE SANPHAM
 (
			ID_SP				INT IDENTITY NOT NULL,
			TENSP				NVARCHAR(100),
			DVT					NVARCHAR(10),			
			ID_LSP				INT,
			SOLUONG				INT,
			DONGIA				FLOAT,
			HINHANH				NVARCHAR(100),
			CONSTRAINT PK_SP PRIMARY KEY(ID_SP),
			CONSTRAINT FK_SP_LOAI FOREIGN KEY (ID_LSP) REFERENCES LOAISANPHAM(ID_LSP),
 );

 CREATE TABLE DANHMUCSANPHAM
(
			ID_NCC			INT NOT NULL,
			ID_SP			INT NOT NULL,
			GIABAN			INT NOT NULL,
			CONSTRAINT PK_DMSP PRIMARY KEY(ID_NCC, ID_SP),
			CONSTRAINT FK_DMSP_NCC FOREIGN KEY (ID_NCC) REFERENCES NHACUNGCAP(ID_NCC),
			CONSTRAINT FK_DMSP_SP FOREIGN KEY (ID_SP) REFERENCES SANPHAM(ID_SP)			
);
 
CREATE TABLE KHUYENMAI
(
			ID_KM			INT IDENTITY NOT NULL,	
			TENKHUYENMAI	NVARCHAR(20),
			NGAYBD			DATE,
			NGAYKT			DATE,
			CHUTHICH		NVARCHAR(100),
			CONSTRAINT PK_KM PRIMARY KEY(ID_KM)
);

CREATE TABLE HOADON
(
			ID_HD			INT IDENTITY NOT NULL,	
			NGAYLAP			DATE,
			ID_DN			VARCHAR(10),
			ID_KH			INT,
			ID_KM			INT,
			TONGTIEN		FLOAT,
			CONSTRAINT PK_HD PRIMARY KEY(ID_HD),
			CONSTRAINT FK_HD_ND FOREIGN KEY (ID_DN) REFERENCES NGUOIDUNG(ID_DN),
			CONSTRAINT FK_HD_KH  FOREIGN KEY (ID_KH) REFERENCES KHACHHANG(ID_KH),
			CONSTRAINT FK_HD_KM FOREIGN KEY (ID_KM) REFERENCES KHUYENMAI(ID_KM)
);

CREATE TABLE CHITIETHOADON
(
			ID_HD			INT NOT NULL,				
			ID_SP			INT,
			SOLUONG			INT,
			DONGIA			FLOAT,
			THANHTIEN		FLOAT,
			CONSTRAINT PK_CTHD PRIMARY KEY(ID_HD,ID_SP),
			CONSTRAINT FK_CTHD_HD FOREIGN KEY (ID_HD) REFERENCES HOADON(ID_HD),
			CONSTRAINT FK_CTHD_SP FOREIGN KEY (ID_SP) REFERENCES SANPHAM(ID_SP)
);

CREATE TABLE PHIEUDAT
 (
			ID_PD				INT IDENTITY NOT NULL,
			ID_NCC				INT,
			ID_DN				VARCHAR(10),
			NGAYLAP				DATE,
			TONGTIEN			FLOAT,
			TINHTRANG			BIT,
			CONSTRAINT PK_PD PRIMARY KEY(ID_PD),
			CONSTRAINT FK_PD_NCC FOREIGN KEY (ID_NCC) REFERENCES NHACUNGCAP(ID_NCC),
			CONSTRAINT FK_PD_ND FOREIGN KEY (ID_DN) REFERENCES NGUOIDUNG(ID_DN)
 );

CREATE TABLE CHITIETPHIEUDAT
(
			ID_PD			INT,
			ID_SP			INT,
			SOLUONG			INT,
			THANHTIEN		FLOAT,
			CONSTRAINT PK_CTPD PRIMARY KEY(ID_PD,ID_SP),
			CONSTRAINT FK_CTPD_PN FOREIGN KEY (ID_PD) REFERENCES PHIEUDAT(ID_PD),
			CONSTRAINT FK_CTPD_SP FOREIGN KEY (ID_SP) REFERENCES SANPHAM(ID_SP)
);

 CREATE TABLE PHIEUNHAP
 (
			ID_PN				INT IDENTITY NOT NULL,
			ID_NCC				INT,
			ID_DN				VARCHAR(10),
			NGAYLAP				DATE,
			TONGTIEN			FLOAT,
			CONSTRAINT PK_PN PRIMARY KEY(ID_PN),
			CONSTRAINT FK_PN_NCC FOREIGN KEY (ID_NCC) REFERENCES NHACUNGCAP(ID_NCC),
			CONSTRAINT FK_PN_ND FOREIGN KEY (ID_DN) REFERENCES NGUOIDUNG(ID_DN),
 );

 CREATE TABLE CHITIETPHIEUNHAP
(
			ID_PN			INT,
			ID_PD			INT,
			ID_SP			INT,
			SOLUONG			INT,
			DONGIANHAP		FLOAT,
			DONGIABAN		FLOAT,
			HANSD			DATE,
			THANHTIEN		FLOAT,
			CONSTRAINT PK_CTPN PRIMARY KEY(ID_PN,ID_SP),
			CONSTRAINT FK_CTPN_PN FOREIGN KEY (ID_PN) REFERENCES PHIEUNHAP(ID_PN),
			CONSTRAINT FK_CTPN_PD FOREIGN KEY (ID_PD) REFERENCES PHIEUDAT(ID_PD),
);


CREATE TABLE PHIEUXUAT
 (
			ID_PX				INT IDENTITY NOT NULL,
			ID_DN				VARCHAR(10),
			NGAYLAP				DATE,
			CONSTRAINT PK_PX PRIMARY KEY(ID_PX),
			CONSTRAINT FK_PX_ND FOREIGN KEY (ID_DN) REFERENCES NGUOIDUNG(ID_DN)
 );

 CREATE TABLE CHITIETPHIEUXUAT
(
			ID_PX			INT,
			ID_SP			INT,
			SOLUONG			INT,
			CONSTRAINT PK_CTPX PRIMARY KEY(ID_PX,ID_SP),
			CONSTRAINT FK_CTPX_PX FOREIGN KEY (ID_PX) REFERENCES PHIEUXUAT(ID_PX),
			CONSTRAINT FK_CTPX_SP FOREIGN KEY (ID_SP) REFERENCES SANPHAM(ID_SP)
);

  CREATE TABLE TONKHO
  (
			ID_SP				INT,
			NGAYTONKHO			DATE,
			SOLUONG				INT,
			TINHTRANG			NVARCHAR(20),
			CONSTRAINT PK_TONKHO PRIMARY KEY(ID_SP,NGAYTONKHO),
			CONSTRAINT FK_TK_SP FOREIGN KEY (ID_SP) REFERENCES SANPHAM(ID_SP)
  );

  CREATE TABLE CHITIETKHUYENMAI
  (
			ID_KM				INT,	
			ID_SP				INT,
			HESOKM				FLOAT,
			TINHTRANG			BIT,
			CONSTRAINT PK_CTKM PRIMARY KEY(ID_KM,ID_SP),
			CONSTRAINT FK_CTKM_KM FOREIGN KEY (ID_KM) REFERENCES KHUYENMAI(ID_KM),
			CONSTRAINT FK_CTKM_SP FOREIGN KEY (ID_SP) REFERENCES SANPHAM(ID_SP)	
  );